spring.application.name=kumnevoistlus

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d7uf2vrtqb8s73cgropg-a.frankfurt-postgres.render.com/kumnevoistlus
spring.datasource.username=kumnevoistlus_user
spring.datasource.password=pxhZHPnYOLq3h7cpQ5Xwu8dxBlk2IUyF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect